version: '3.8'

services:
  app:
    build: ./backend  # Build from Dockerfile inside backend/
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  postgres_db:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
